### ISSUE TITLE
Why nothing on Flathub?

### ISSUE THREAD

**Issue by mbugni** [MadDeCoDeR/BFA-flatpak-scripts#1]
I can't find any app submission for this.

**Comment by MadDeCoDeR** [comment]
Hi, I'm still testing it and sadly there might be some issues with it.
Issues mostly related to open platform and Steam and to loading some assets from DOOM 3 mods.
Most of the work for a flatpak release is done for the engine's and script's part

**Comment by mbugni** [comment]
Move out Marine! Your fans [are waiting...](https://github.com/flathub/io.github.RobertBeckebans.RBDoom3BFG-GL/issues/2)

BTW: do you plan to release the engine stand alone?
